"""
test_n6_30a_plug_and_play_swarm_memory_intake.py

Structural tests for the N+6.30A plug-and-play swarm and memory intake.
Validates that all required files exist and contain the expected safety
invariants, tool registry structure, and no forbidden content.
Pure stdlib; no network; no installs; no agent launching.
"""

import json
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
TOOL_INTAKE = REPO_ROOT / "14_context" / "tool_intake"
DOCS = REPO_ROOT / "docs"
CONTEXT = REPO_ROOT / "14_context"
HANDOFFS = REPO_ROOT / "14_context" / "agent_handoff_vault" / "02_Agent_Handoffs"


class TestRequiredFilesExist(unittest.TestCase):
    def _check(self, path: Path) -> None:
        self.assertTrue(path.is_file(), msg=f"missing: {path.relative_to(REPO_ROOT)}")

    def test_main_doc(self):
        self._check(DOCS / "GHOTI_N6_30A_PLUG_AND_PLAY_SWARM_MEMORY_INTAKE.md")

    def test_tool_ranking_md(self):
        self._check(TOOL_INTAKE / "plug_and_play_swarm_tools_n6_30a.md")

    def test_tool_registry_json(self):
        self._check(TOOL_INTAKE / "plug_and_play_swarm_tools_n6_30a.json")

    def test_ecc_ruflo_trial_plan(self):
        self._check(TOOL_INTAKE / "ecc_ruflo_swarm_trial_plan_n6_30a.md")

    def test_cua_ui_tars_plan(self):
        self._check(TOOL_INTAKE / "cua_ui_tars_computer_use_trial_plan_n6_30a.md")

    def test_memory_intake(self):
        self._check(TOOL_INTAKE / "claude_mem_obsidian_mempalace_intake_n6_30a.md")

    def test_tier_one_status(self):
        self._check(TOOL_INTAKE / "tier_one_priority_status_n6_30a.md")

    def test_handoff(self):
        self._check(HANDOFFS / "NEXT_PLUG_AND_PLAY_TOOLS_TASK.md")

    def test_context_snapshot(self):
        self._check(CONTEXT / "claude_n6_30a_plug_and_play_swarm_memory_intake.md")


class TestToolRegistryJson(unittest.TestCase):
    def setUp(self):
        path = TOOL_INTAKE / "plug_and_play_swarm_tools_n6_30a.json"
        self.data = json.loads(path.read_text(encoding="utf-8"))

    def test_milestone_field(self):
        self.assertEqual(self.data["milestone"], "N+6.30A")

    def test_tools_is_list(self):
        self.assertIsInstance(self.data["tools"], list)
        self.assertGreater(len(self.data["tools"]), 5)

    def test_each_tool_has_required_fields(self):
        required = {"id", "name", "tier", "ghoti_default", "risk_level"}
        for tool in self.data["tools"]:
            missing = required - set(tool.keys())
            self.assertEqual(missing, set(), msg=f"Tool '{tool.get('id')}' missing: {missing}")

    def test_ruflo_is_deferred(self):
        ruflo = next(t for t in self.data["tools"] if "ruflo" in t["id"].lower())
        self.assertIn(ruflo["tier"], {"defer", "avoid", "should_stay_disabled"})
        self.assertIn("supply_chain_incidents", ruflo)
        self.assertGreater(len(ruflo["supply_chain_incidents"]), 0)

    def test_subagents_is_active(self):
        sub = next(t for t in self.data["tools"] if "subagent" in t["id"].lower())
        self.assertIn(sub["tier"], {"use_now_main_profile", "guidance_only"})

    def test_dynamic_workflows_is_deferred(self):
        dw = next(t for t in self.data["tools"] if "dynamic" in t["id"].lower())
        self.assertIn(dw["tier"], {"defer", "should_stay_disabled"})

    def test_agent_teams_is_deferred(self):
        at = next(t for t in self.data["tools"] if "agent_teams" in t["id"].lower())
        self.assertIn(at["tier"], {"defer", "should_stay_disabled"})

    def test_dependency_state_present(self):
        deps = self.data["dependencies"]
        self.assertIn("n6_27b", deps)
        self.assertIn("n6_28b", deps)
        self.assertIn("n6_29b", deps)
        self.assertIn("merged", deps["n6_27b"])
        self.assertIn("merged", deps["n6_28b"])
        self.assertIn("not_merged", deps["n6_29b"])

    def test_no_fabricated_urls(self):
        # Every tool with a source URL must record license_verified or source_needed
        text = json.dumps(self.data)
        # Verify that the data is JSON-serializable and round-trips correctly
        self.assertEqual(json.loads(text), self.data)


class TestNoForbiddenContent(unittest.TestCase):
    """Ensure committed files contain no AI attribution, secrets, or live tool launches."""

    def _all_new_files(self):
        files = []
        for pattern in ["docs/GHOTI_N6_30A_*.md", "14_context/tool_intake/*n6_30a*",
                         "14_context/claude_n6_30a_*.md",
                         "14_context/agent_handoff_vault/**/NEXT_PLUG*"]:
            files.extend(REPO_ROOT.glob(pattern))
        return files

    def test_no_ai_attribution_trailers(self):
        forbidden = [
            "co-authored-by claude",
            "co-authored-by gpt",
            "generated with claude",
            "generated by claude",
            "generated with chatgpt",
        ]
        for fpath in self._all_new_files():
            content = fpath.read_text(encoding="utf-8").lower()
            for phrase in forbidden:
                self.assertNotIn(
                    phrase, content,
                    msg=f"AI attribution found in {fpath.name}: '{phrase}'"
                )

    def test_no_real_secrets_committed(self):
        secret_patterns = ["api_key =", "token =", "password =", "secret =",
                           "bearer ", "cookie:", ".env"]
        for fpath in self._all_new_files():
            content = fpath.read_text(encoding="utf-8").lower()
            for pattern in secret_patterns:
                # Allow mentions in documentation context (e.g. "never commit api_key")
                # but flag obvious assignments/values
                if f'"{pattern}' in content or f"'{pattern}" in content:
                    self.fail(f"Possible secret in {fpath.name}: '{pattern}'")

    def test_no_live_launch_instructions(self):
        """Ensure no file instructs live agent launching."""
        forbidden_actions = [
            "enable agent teams",
            "enable dynamic workflows",
            "enable mcp",
            "install ruflo",
            "npm install ruflo",
            "pip install ruflo",
        ]
        for fpath in self._all_new_files():
            content = fpath.read_text(encoding="utf-8").lower()
            for action in forbidden_actions:
                self.assertNotIn(
                    action, content,
                    msg=f"Forbidden live-launch instruction in {fpath.name}: '{action}'"
                )


class TestSafetyInvariants(unittest.TestCase):
    def test_ruflo_never_install_stated(self):
        trial_plan = (TOOL_INTAKE / "ecc_ruflo_swarm_trial_plan_n6_30a.md").read_text(encoding="utf-8").lower()
        self.assertIn("defer indefinitely", trial_plan)
        self.assertIn("never install", trial_plan)

    def test_computer_use_adapter_not_touched(self):
        """N+6.29B not merged: computer_use_adapter files must not exist in this branch's additions."""
        # These files should be present on the branch (committed earlier) but this
        # milestone (N+6.30A) must NOT add new ones to the computer_use_adapter paths.
        # We verify the N+6.30A doc explicitly states the dependency.
        doc = (DOCS / "GHOTI_N6_30A_PLUG_AND_PLAY_SWARM_MEMORY_INTAKE.md").read_text(encoding="utf-8")
        self.assertIn("computer_use_adapter", doc)
        self.assertIn("not merged", doc.lower())

    def test_pao_app_separate_from_agent_memory(self):
        mem_doc = (TOOL_INTAKE / "claude_mem_obsidian_mempalace_intake_n6_30a.md").read_text(encoding="utf-8").lower()
        self.assertIn("pao app", mem_doc)
        self.assertIn("separate", mem_doc)
        self.assertIn("tier-1-last", mem_doc)

    def test_tier_one_status_covers_rust(self):
        tier_doc = (TOOL_INTAKE / "tier_one_priority_status_n6_30a.md").read_text(encoding="utf-8").lower()
        self.assertIn("n+6.28b", tier_doc)
        self.assertIn("merged", tier_doc)

    def test_source_needed_tools_listed(self):
        registry = json.loads((TOOL_INTAKE / "plug_and_play_swarm_tools_n6_30a.json").read_text(encoding="utf-8"))
        source_needed = [t for t in registry["tools"] if t.get("source_needed", False)]
        source_needed_ids = {t["id"] for t in source_needed}
        for expected_id in ("claude_mem", "obsidian_skills", "mempalace_agent", "ui_tars"):
            self.assertIn(
                expected_id, source_needed_ids,
                msg=f"Expected source_needed tool '{expected_id}' not in registry"
            )

    def test_main_doc_lists_all_files(self):
        doc = (DOCS / "GHOTI_N6_30A_PLUG_AND_PLAY_SWARM_MEMORY_INTAKE.md").read_text(encoding="utf-8")
        expected_files = [
            "plug_and_play_swarm_tools_n6_30a.md",
            "plug_and_play_swarm_tools_n6_30a.json",
            "ecc_ruflo_swarm_trial_plan_n6_30a.md",
            "cua_ui_tars_computer_use_trial_plan_n6_30a.md",
            "claude_mem_obsidian_mempalace_intake_n6_30a.md",
            "tier_one_priority_status_n6_30a.md",
            "NEXT_PLUG_AND_PLAY_TOOLS_TASK.md",
            "test_n6_30a_plug_and_play_swarm_memory_intake.py",
            "claude_n6_30a_plug_and_play_swarm_memory_intake.md",
        ]
        for fname in expected_files:
            self.assertIn(fname, doc, msg=f"Main doc missing reference to '{fname}'")


if __name__ == "__main__":
    unittest.main(verbosity=2)
