"""
test_n6_36a_first_runnable_agent_system_adapter.py — N+6.36A test suite.

Covers:
- No third-party code committed
- Sandbox repos are gitignored
- Selected target is recorded (claude_swarm)
- No-op / dry-run plan works
- Live launch / live agent launch blocked
- Hook install blocked
- MCP blocked
- Browser / computer-use blocked
- Account actions blocked
- Secrets blocked
- Auto-submit blocked
- Agent Arena shaped output: simulation=true, live_execution=false
- No real local machine paths in committed files
- No AI attribution
- No Claude/GPT contributor/co-author wording
"""
from __future__ import annotations

import ast
import inspect
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

_ADAPTER_DIR = Path(__file__).resolve().parent.parent.parent.parent / "03_scripts" / "agent_system_adapter"
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent

if str(_ADAPTER_DIR) not in sys.path:
    sys.path.insert(0, str(_ADAPTER_DIR))

import ghoti_agent_system_adapter as _adapter


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sandbox() -> Path:
    return _repo_root() / "21_repos" / "third_party_runtime_sandbox"


def _repo_root() -> Path:
    return _REPO_ROOT


# ---------------------------------------------------------------------------
# 1. Source code safety
# ---------------------------------------------------------------------------

class TestSourceCodeSafety(unittest.TestCase):
    def test_adapter_does_not_import_third_party_engines(self):
        src = inspect.getsource(_adapter)
        tree = ast.parse(src)
        forbidden = {"claude_swarm", "am_will_swarms", "clawteam", "ruflo",
                     "ecc", "paperclip", "hermes_paperclip"}
        for node in ast.walk(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                for alias in getattr(node, "names", []):
                    name = alias.name or ""
                    self.assertFalse(
                        any(f in name for f in forbidden),
                        f"Adapter imports third-party engine code: {name}",
                    )

    def test_adapter_no_subprocess_launch(self):
        src = inspect.getsource(_adapter)
        tree = ast.parse(src)
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = node.func
                if isinstance(func, ast.Attribute) and func.attr in ("run", "call", "Popen"):
                    if isinstance(func.value, ast.Name) and func.value.id == "subprocess":
                        self.fail("Adapter uses subprocess to launch external processes")

    def test_adapter_no_live_agent_launch_string(self):
        src = inspect.getsource(_adapter)
        forbidden_strings = ["live_launch=True", "live_agent_launch=True"]
        for s in forbidden_strings:
            self.assertNotIn(s, src, f"Adapter contains: {s}")

    def test_no_ai_attribution_in_adapter(self):
        path = _ADAPTER_DIR / "ghoti_agent_system_adapter.py"
        text = path.read_text()
        forbidden = [
            "co-authored-by claude",
            "co-authored-by gpt",
            "generated with claude",
            "generated by claude",
            "written by claude",
            "claude code",
        ]
        lower = text.lower()
        for f in forbidden:
            self.assertNotIn(f, lower, f"AI attribution found: {f!r}")


# ---------------------------------------------------------------------------
# 2. Sandbox isolation
# ---------------------------------------------------------------------------

class TestSandboxIsolation(unittest.TestCase):
    def test_sandbox_repos_gitignored(self):
        result = subprocess.run(
            ["git", "-C", str(_repo_root()), "ls-files",
             "21_repos/third_party_runtime_sandbox/claude_swarm"],
            capture_output=True, text=True,
        )
        self.assertEqual(result.stdout.strip(), "",
                         "claude_swarm is tracked by git — should be gitignored")

    def test_no_claude_swarm_source_committed(self):
        result = subprocess.run(
            ["git", "-C", str(_repo_root()), "ls-files",
             "21_repos/third_party_runtime_sandbox/"],
            capture_output=True, text=True,
        )
        tracked = [f for f in result.stdout.splitlines()
                   if not f.endswith(".gitkeep")]
        self.assertEqual(tracked, [],
                         f"Third-party files are tracked: {tracked}")

    def test_check_rejects_sandbox_outside_allowed_root(self):
        with tempfile.TemporaryDirectory() as tmp:
            result = _adapter._run_check(Path(tmp))
        self.assertFalse(result["ok"])
        self.assertEqual(result["error"], "sandbox_outside_allowed_root")

    def test_smoke_rejects_sandbox_outside_allowed_root(self):
        with tempfile.TemporaryDirectory() as tmp:
            result = _adapter._run_smoke(Path(tmp))
        self.assertFalse(result["ok"])
        self.assertEqual(result["error"], "sandbox_outside_allowed_root")


# ---------------------------------------------------------------------------
# 3. Target detection
# ---------------------------------------------------------------------------

class TestTargetDetection(unittest.TestCase):
    def test_primary_target_is_claude_swarm(self):
        self.assertEqual(_adapter._PRIMARY_TARGET, "claude_swarm")

    def test_priority_list_starts_claude_swarm(self):
        self.assertEqual(_adapter._TARGET_PRIORITY[0], "claude_swarm")

    def test_detection_finds_claude_swarm_if_present(self):
        sandbox = _sandbox()
        if not (sandbox / "claude_swarm").exists():
            self.skipTest("claude_swarm not in sandbox")
        result = _adapter._detect_target(sandbox)
        self.assertEqual(result["selected"], "claude_swarm")
        self.assertTrue(result["present"])

    def test_detection_returns_none_when_sandbox_empty(self, tmp_path=None):
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            result = _adapter._detect_target(Path(tmp))
            self.assertIsNone(result["selected"])
            self.assertFalse(result["present"])

    def test_selection_rationale_recorded(self):
        self.assertIn("claude_swarm", _adapter._SELECTION_RATIONALE)
        self.assertIn("MOST_READY", _adapter._SELECTION_RATIONALE["claude_swarm"])

    def test_all_deferred_systems_documented(self):
        for system in ["am_will_swarms", "clawteam", "ruflo", "ecc", "paperclip",
                       "hermes_paperclip_adapter"]:
            self.assertIn(system, _adapter._SELECTION_RATIONALE,
                          f"Missing rationale for deferred system: {system}")


# ---------------------------------------------------------------------------
# 4. No-op / dry-run plan
# ---------------------------------------------------------------------------

class TestNoopPlan(unittest.TestCase):
    def _metadata(self) -> dict:
        sandbox = _sandbox()
        if not (sandbox / "claude_swarm").exists():
            return {
                "target_id": "claude_swarm",
                "path": str(sandbox / "claude_swarm"),
                "version": "0.2.0",
                "entry_point": "claude-swarm",
                "dry_run_flag": "--dry-run",
                "safe_command": None,
                "candidate_external_command": 'claude-swarm --dry-run "describe task here"',
                "blocked_command": 'claude-swarm "describe task here"',
            }
        return _adapter._read_metadata(sandbox / "claude_swarm", "claude_swarm")

    def test_plan_is_dry_run(self):
        plan = _adapter._build_noop_plan(self._metadata())
        self.assertTrue(plan["dry_run"])

    def test_plan_live_launch_false(self):
        plan = _adapter._build_noop_plan(self._metadata())
        self.assertFalse(plan["live_launch"])

    def test_plan_live_agent_launch_false(self):
        plan = _adapter._build_noop_plan(self._metadata())
        self.assertFalse(plan["live_agent_launch"])

    def test_plan_requires_human_approval(self):
        plan = _adapter._build_noop_plan(self._metadata())
        self.assertTrue(plan["requires_human_approval"])

    def test_plan_capabilities_safe(self):
        plan = _adapter._build_noop_plan(self._metadata())
        for cap in plan["capabilities"]:
            self.assertNotIn(cap, _adapter._GLOBALLY_BLOCKED,
                             f"Unsafe capability in plan: {cap}")

    def test_plan_actions_all_dry_run(self):
        plan = _adapter._build_noop_plan(self._metadata())
        for action in plan["actions"]:
            self.assertTrue(action["dry_run"], f"Action not dry_run: {action}")

    def test_plan_synthetic_swarm_config_empty_agents(self):
        plan = _adapter._build_noop_plan(self._metadata())
        self.assertEqual(plan["synthetic_swarm_config"]["agents"], {})


# ---------------------------------------------------------------------------
# 5. Blocked capabilities pre-filter
# ---------------------------------------------------------------------------

class TestBlockedCapabilities(unittest.TestCase):
    def _plan_with_cap(self, cap: str) -> dict:
        return {
            "plan_id": "test",
            "capabilities": [cap],
            "actions": [],
            "live_launch": False,
            "live_agent_launch": False,
        }

    def test_hooks_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("hooks"))
        self.assertFalse(result["allowed"])
        self.assertIn("hooks", result["blocked_capabilities"])

    def test_mcp_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("mcp"))
        self.assertFalse(result["allowed"])
        self.assertIn("mcp", result["blocked_capabilities"])

    def test_browser_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("browser"))
        self.assertFalse(result["allowed"])
        self.assertIn("browser", result["blocked_capabilities"])

    def test_account_actions_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("account_actions"))
        self.assertFalse(result["allowed"])
        self.assertIn("account_actions", result["blocked_capabilities"])

    def test_secrets_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("secrets"))
        self.assertFalse(result["allowed"])
        self.assertIn("secrets", result["blocked_capabilities"])

    def test_auto_submit_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("auto_submit"))
        self.assertFalse(result["allowed"])
        self.assertIn("auto_submit", result["blocked_capabilities"])

    def test_docker_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("docker"))
        self.assertFalse(result["allowed"])
        self.assertIn("docker", result["blocked_capabilities"])

    def test_live_agent_launch_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("live_agent_launch"))
        self.assertFalse(result["allowed"])

    def test_live_launch_flag_blocked(self):
        plan = {
            "plan_id": "test",
            "capabilities": [],
            "actions": [],
            "live_launch": True,
            "live_agent_launch": False,
        }
        result = _adapter._validate_plan(plan)
        self.assertFalse(result["allowed"])
        self.assertIn("live_launch", result["blocked_capabilities"])

    def test_shell_execution_blocked(self):
        result = _adapter._validate_plan(self._plan_with_cap("shell_execution"))
        self.assertFalse(result["allowed"])

    def test_missing_dual_gate_adapter_fails_closed(self):
        plan = self._plan_with_cap("plan_render")
        with tempfile.TemporaryDirectory() as tmp:
            original = _adapter._repo_root
            try:
                _adapter._repo_root = lambda: Path(tmp)
                result = _adapter._validate_plan(plan)
            finally:
                _adapter._repo_root = original
        self.assertFalse(result["allowed"])
        self.assertEqual(result["reason"], "adapter_not_found_fail_closed")


# ---------------------------------------------------------------------------
# 6. Agent Arena status shape
# ---------------------------------------------------------------------------

class TestArenaStatus(unittest.TestCase):
    def test_safety_block_simulation_true(self):
        self.assertTrue(_adapter._SAFETY_BLOCK["simulation"])

    def test_safety_block_live_execution_false(self):
        self.assertFalse(_adapter._SAFETY_BLOCK["live_execution"])

    def test_safety_block_live_computer_use_false(self):
        self.assertFalse(_adapter._SAFETY_BLOCK["live_computer_use_enabled"])

    def test_safety_block_hooks_disabled(self):
        self.assertFalse(_adapter._SAFETY_BLOCK["hooks_enabled"])

    def test_safety_block_live_agent_launch_false(self):
        self.assertFalse(_adapter._SAFETY_BLOCK["live_agent_launch"])

    def test_safety_block_third_party_not_executed(self):
        self.assertFalse(_adapter._SAFETY_BLOCK["third_party_code_executed"])
        self.assertFalse(_adapter._SAFETY_BLOCK["third_party_code_imported"])

    def test_check_mode_returns_safety_block(self):
        result = _adapter._run_check()
        self.assertIn("safety_block", result)
        self.assertTrue(result["safety_block"]["simulation"])
        self.assertFalse(result["safety_block"]["live_execution"])


# ---------------------------------------------------------------------------
# 7. Check mode
# ---------------------------------------------------------------------------

class TestCheckMode(unittest.TestCase):
    def test_check_ok(self):
        result = _adapter._run_check()
        self.assertTrue(result["ok"])

    def test_check_milestone(self):
        result = _adapter._run_check()
        self.assertEqual(result["milestone"], "N+6.36A")

    def test_check_has_globally_blocked(self):
        result = _adapter._run_check()
        self.assertIn("globally_blocked_capabilities", result)
        for cap in ["hooks", "mcp", "docker", "browser", "secrets"]:
            self.assertIn(cap, result["globally_blocked_capabilities"])

    def test_check_has_live_approval_checklist(self):
        result = _adapter._run_check()
        self.assertIn("live_approval_checklist", result)
        self.assertGreater(len(result["live_approval_checklist"]), 0)


# ---------------------------------------------------------------------------
# 8. Smoke mode (requires sandbox)
# ---------------------------------------------------------------------------

class TestSmokeMode(unittest.TestCase):
    def setUp(self):
        self.sandbox = _sandbox()
        if not (self.sandbox / "claude_swarm").exists():
            self.skipTest("claude_swarm not in sandbox")

    def test_smoke_accepted(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        self.assertTrue(result.get("accepted", False),
                        f"Expected accepted=True, got: {result.get('validation')}")

    def test_smoke_proves_dual_gate_participated(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        validation = result["validation"]
        self.assertTrue(validation["rust_policy_bridge_ready"])
        self.assertTrue(validation["rust_allowed"])
        self.assertTrue(validation["rust_policy_decision"]["allowed"])

    def test_smoke_selected_target_is_claude_swarm(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        self.assertEqual(result["selected_target"], "claude_swarm")

    def test_smoke_does_not_approve_external_safe_command(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        self.assertIsNone(result.get("safe_command"))
        self.assertFalse(result["candidate_external_command_approved"])

    def test_smoke_records_blocked_candidate_external_command(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        candidate = result.get("candidate_external_command", "")
        self.assertIn("--dry-run", candidate)
        self.assertIn("provider/API audit", result["candidate_external_command_warning"])

    def test_smoke_has_blocked_command(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        blocked = result.get("blocked_command", "")
        self.assertIn("claude-swarm", blocked)
        self.assertNotIn("--dry-run", blocked)

    def test_smoke_metadata_license_mit(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        self.assertEqual(result["metadata"]["license"], "MIT")

    def test_smoke_metadata_no_paths_outside_sandbox(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        metadata = result.get("metadata", {})
        for field in ["path", "safe_command", "candidate_external_command", "blocked_command", "readme_excerpt"]:
            value = metadata.get(field, "") or ""
            for p in ["/home/user/", "C:\\Users\\", "/root/"]:
                self.assertNotIn(p, value,
                                 f"Machine path in metadata.{field}: {p}")
        self.assertEqual(
            metadata["path"],
            "21_repos/third_party_runtime_sandbox/claude_swarm",
        )

    def test_check_uses_repo_relative_sandbox_path(self):
        result = _adapter._run_check(sandbox=self.sandbox)
        self.assertEqual(result["sandbox_root"], "21_repos/third_party_runtime_sandbox")

    def test_smoke_safety_block_correct(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        sb = result["safety_block"]
        self.assertTrue(sb["simulation"])
        self.assertFalse(sb["live_execution"])
        self.assertFalse(sb["live_agent_launch"])
        self.assertFalse(sb["third_party_code_executed"])
        self.assertFalse(sb["third_party_code_imported"])

    def test_smoke_has_deferred_systems(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        self.assertIn("deferred_systems", result)
        deferred = result["deferred_systems"]
        for system in ["am_will_swarms", "ruflo", "ecc", "paperclip"]:
            self.assertIn(system, deferred)

    def test_smoke_metadata_third_party_not_imported(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        self.assertFalse(result["metadata"]["third_party_code_imported"])
        self.assertFalse(result["metadata"]["third_party_code_executed"])

    def test_external_dry_run_truth_is_recorded(self):
        result = _adapter._run_smoke(sandbox=self.sandbox)
        metadata = result["metadata"]
        self.assertTrue(metadata["external_dry_run_requires_api_key"])
        self.assertTrue(metadata["external_dry_run_calls_provider"])
        self.assertTrue(metadata["external_dry_run_writes_session"])


if __name__ == "__main__":
    unittest.main()
