"""
test_n6_37a_claude_swarm_isolated_dry_run.py  --  N+6.37A test suite.

Tests:
- wrapper refuses live mode (no safe flag)
- wrapper requires dry-run or demo flag
- wrapper refuses API keys
- wrapper refuses account/auth paths
- wrapper refuses non-scratch output inside repo
- wrapper refuses live launch flags
- no third-party code committed
- no secrets in adapter source
- no AI attribution in adapter source
- Agent-Arena-shaped output has simulation=true, live_execution=false
- dry-run execution is BLOCKED (requires API key)
- --version probe is safe
- tool_detection works
- start condition gap documented
"""
from __future__ import annotations

import ast
import inspect
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

_WRAPPER_DIR = (
    Path(__file__).resolve().parent.parent.parent.parent
    / "03_scripts"
    / "claude_swarm_dry_run"
)
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent

if str(_WRAPPER_DIR) not in sys.path:
    sys.path.insert(0, str(_WRAPPER_DIR))

import ghoti_claude_swarm_dry_run as _wrapper


def _repo_root() -> Path:
    return _REPO_ROOT


# ---------------------------------------------------------------------------
# 1. Source safety
# ---------------------------------------------------------------------------

class TestSourceSafety(unittest.TestCase):
    def test_no_api_key_hardcoded(self):
        path = _WRAPPER_DIR / "ghoti_claude_swarm_dry_run.py"
        text = path.read_text().lower()
        for token in ["sk-ant-", "anthropic_api_key=", "api_key="]:
            if token in text:
                # Allow the constant name itself
                if token == "anthropic_api_key=" and "_API_KEY_ENV_VARS" in path.read_text():
                    continue
                self.fail(f"Possible API key in source: {token!r}")

    def test_no_ai_attribution(self):
        path = _WRAPPER_DIR / "ghoti_claude_swarm_dry_run.py"
        text = path.read_text().lower()
        for phrase in [
            "co-authored-by claude",
            "generated with claude",
            "generated by claude",
            "written by claude",
        ]:
            self.assertNotIn(phrase, text, f"AI attribution: {phrase!r}")

    def test_wrapper_does_not_import_claude_swarm(self):
        src = inspect.getsource(_wrapper)
        tree = ast.parse(src)
        for node in ast.walk(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                for alias in getattr(node, "names", []):
                    name = alias.name or ""
                    self.assertNotIn(
                        "claude_swarm", name,
                        f"Wrapper directly imports claude_swarm: {name}",
                    )

    def test_no_third_party_code_committed(self):
        result = subprocess.run(
            ["git", "-C", str(_repo_root()), "ls-files",
             "21_repos/third_party_runtime_sandbox/claude_swarm"],
            capture_output=True, text=True,
        )
        tracked = result.stdout.strip()
        self.assertEqual(tracked, "", f"claude_swarm tracked by git: {tracked}")

    def test_safety_constants_present(self):
        self.assertIn("ANTHROPIC_API_KEY", _wrapper._API_KEY_ENV_VARS)
        self.assertGreater(len(_wrapper._API_KEY_ENV_VARS), 0)


# ---------------------------------------------------------------------------
# 2. Live mode refusal
# ---------------------------------------------------------------------------

class TestLiveModeRefusal(unittest.TestCase):
    def test_no_safe_flag_is_blocked(self):
        result = _wrapper._validate_invocation([])
        self.assertFalse(result["allowed"])
        self.assertTrue(any("no_safe_mode_flag" in r for r in result["blocked_reasons"]))

    def test_live_launch_without_demo_blocked(self):
        result = _wrapper._validate_invocation(["--some-task"])
        self.assertFalse(result["allowed"])

    def test_version_flag_allowed(self):
        result = _wrapper._validate_invocation(["--version"])
        self.assertTrue(result["allowed"], f"--version should be allowed: {result}")

    def test_demo_flag_allowed_no_api_key(self):
        clean_env = {k: v for k, v in os.environ.items()
                     if k not in _wrapper._API_KEY_ENV_VARS}
        original = {k: os.environ.pop(k, None) for k in _wrapper._API_KEY_ENV_VARS}
        try:
            result = _wrapper._validate_invocation(["--demo", "--no-ui"])
            self.assertTrue(result["allowed"], f"--demo should be allowed: {result}")
        finally:
            for k, v in original.items():
                if v is not None:
                    os.environ[k] = v


# ---------------------------------------------------------------------------
# 3. API key refusal
# ---------------------------------------------------------------------------

class TestApiKeyRefusal(unittest.TestCase):
    def test_api_key_in_env_blocks_invocation(self):
        os.environ["ANTHROPIC_API_KEY"] = "test-key-fake"
        try:
            result = _wrapper._validate_invocation(["--demo", "--no-ui"])
            self.assertFalse(result["allowed"])
            self.assertTrue(any("api_key_present" in r for r in result["blocked_reasons"]))
        finally:
            del os.environ["ANTHROPIC_API_KEY"]

    def test_check_api_keys_finds_set_key(self):
        os.environ["ANTHROPIC_API_KEY"] = "fake-key-xyz"
        try:
            keys = _wrapper._check_api_keys_in_env()
            self.assertIn("ANTHROPIC_API_KEY", keys)
        finally:
            del os.environ["ANTHROPIC_API_KEY"]

    def test_check_api_keys_empty_when_none_set(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        keys = _wrapper._check_api_keys_in_env()
        self.assertEqual(keys, [])

    def test_dry_run_blocked_reason_documented(self):
        result = _wrapper._validate_invocation(["--dry-run"])
        self.assertFalse(result["allowed"])
        self.assertTrue(
            any("dry_run_requires_api_key" in r or "api_key" in r
                for r in result["blocked_reasons"]),
            f"Expected dry_run API key block, got: {result['blocked_reasons']}",
        )


# ---------------------------------------------------------------------------
# 4. Non-scratch output refusal
# ---------------------------------------------------------------------------

class TestScratchPathRefusal(unittest.TestCase):
    def test_scratch_inside_repo_blocked(self):
        repo_scratch = str(_repo_root() / "tmp_test_scratch")
        result = _wrapper._validate_invocation(["--demo", "--no-ui"], scratch=repo_scratch)
        self.assertFalse(result["allowed"])
        self.assertTrue(
            any("scratch_inside_repo" in r for r in result["blocked_reasons"]),
            f"Expected scratch_inside_repo block: {result['blocked_reasons']}",
        )

    def test_scratch_outside_repo_allowed(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        with tempfile.TemporaryDirectory() as tmp:
            result = _wrapper._validate_invocation(["--demo", "--no-ui"], scratch=tmp)
            self.assertTrue(result["allowed"], f"External scratch should be allowed: {result}")


# ---------------------------------------------------------------------------
# 5. Agent Arena status shape
# ---------------------------------------------------------------------------

class TestArenaStatus(unittest.TestCase):
    def test_safety_block_simulation_true(self):
        self.assertTrue(_wrapper._SAFETY_BLOCK["simulation"])

    def test_safety_block_live_execution_false(self):
        self.assertFalse(_wrapper._SAFETY_BLOCK["live_execution"])

    def test_safety_block_live_agent_launch_false(self):
        self.assertFalse(_wrapper._SAFETY_BLOCK["live_agent_launch"])

    def test_safety_block_api_key_used_false(self):
        self.assertFalse(_wrapper._SAFETY_BLOCK["api_key_used"])

    def test_safety_block_network_attempted_false(self):
        self.assertFalse(_wrapper._SAFETY_BLOCK["network_attempted"])

    def test_check_mode_has_safety_block(self):
        result = _wrapper._run_check()
        self.assertIn("safety_block", result)
        self.assertTrue(result["safety_block"]["simulation"])
        self.assertFalse(result["safety_block"]["live_execution"])


# ---------------------------------------------------------------------------
# 6. Check mode
# ---------------------------------------------------------------------------

class TestCheckMode(unittest.TestCase):
    def test_check_ok(self):
        result = _wrapper._run_check()
        self.assertTrue(result["ok"])

    def test_check_milestone(self):
        result = _wrapper._run_check()
        self.assertEqual(result["milestone"], "N+6.37A")

    def test_check_documents_dry_run_blocked(self):
        result = _wrapper._run_check()
        self.assertIn("dry_run_flag_status", result)
        self.assertIn("BLOCKED", result["dry_run_flag_status"])

    def test_check_has_blocked_command(self):
        result = _wrapper._run_check()
        self.assertIn("blocked_command", result)
        self.assertIn("--dry-run", result["blocked_command"])

    def test_check_start_conditions_documented(self):
        result = _wrapper._run_check()
        self.assertIn("start_conditions", result)
        sc = result["start_conditions"]
        self.assertIn("n6_35b_on_main", sc)
        self.assertIn("n6_36b_on_main", sc)

    def test_check_has_safe_command(self):
        result = _wrapper._run_check()
        self.assertIn("safe_command", result)
        # Static-only: safe path is metadata inspection, not CLI execution.
        self.assertIn("static", result["safe_command"].lower())


# ---------------------------------------------------------------------------
# 7. Probe mode
# ---------------------------------------------------------------------------

class TestProbeMode(unittest.TestCase):
    def test_probe_reports_not_installed(self):
        result = _wrapper._run_probe()
        self.assertIn("execution_status", result)
        self.assertIn(result["execution_status"],
                      [_wrapper._STATUS_NOT_INSTALLED, _wrapper._STATUS_PROBE_OK,
                       _wrapper._STATUS_BLOCKED])

    def test_probe_has_safety_block(self):
        result = _wrapper._run_probe()
        self.assertIn("safety_block", result)

    def test_probe_blocked_if_api_key_set(self):
        os.environ["ANTHROPIC_API_KEY"] = "fake"
        try:
            result = _wrapper._run_probe()
            self.assertEqual(result["execution_status"], _wrapper._STATUS_BLOCKED)
        finally:
            del os.environ["ANTHROPIC_API_KEY"]

    def test_probe_no_api_key_used(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _wrapper._run_probe()
        sb = result.get("safety_block", {})
        self.assertFalse(sb.get("api_key_used", True))

    def test_probe_milestone_correct(self):
        result = _wrapper._run_probe()
        self.assertEqual(result["milestone"], "N+6.37A")


# ---------------------------------------------------------------------------
# 8. Dry-run status is BLOCKED (documented)
# ---------------------------------------------------------------------------

class TestDryRunBlockedStatus(unittest.TestCase):
    def test_dry_run_requires_api_key(self):
        # Verify the wrapper's own documentation of why --dry-run is blocked
        result = _wrapper._run_check()
        status = result.get("dry_run_flag_status", "")
        self.assertIn("BLOCKED", status)
        self.assertIn("API", status.upper())

    def test_blocked_command_is_dry_run(self):
        result = _wrapper._run_check()
        self.assertIn("--dry-run", result.get("blocked_command", ""))

    def test_dry_run_validation_blocked(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _wrapper._validate_invocation(["--dry-run"])
        self.assertFalse(result["allowed"])


# ---------------------------------------------------------------------------
# 9. Demo mode (not installed -> graceful)
# ---------------------------------------------------------------------------

class TestDemoModeGraceful(unittest.TestCase):
    def test_demo_not_installed_returns_not_installed(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _wrapper._run_demo_mode()
        # Either not installed or blocked (no API key) or demo_ok if installed
        self.assertIn(result.get("execution_status", ""),
                      [_wrapper._STATUS_NOT_INSTALLED, _wrapper._STATUS_DEMO_OK,
                       _wrapper._STATUS_BLOCKED, _wrapper._STATUS_DEMO_FAILED])

    def test_demo_blocked_when_api_key_set(self):
        os.environ["ANTHROPIC_API_KEY"] = "fake-key"
        try:
            result = _wrapper._run_demo_mode()
            self.assertEqual(result["execution_status"], _wrapper._STATUS_BLOCKED)
        finally:
            del os.environ["ANTHROPIC_API_KEY"]

    def test_demo_emits_static_plan_no_api_key(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _wrapper._run_demo_mode()
        self.assertEqual(result["execution_status"], _wrapper._STATUS_DEMO_OK)
        self.assertIn("demo_plan", result)
        self.assertEqual(result["demo_plan"]["source"], "static_simulation")


# ---------------------------------------------------------------------------
# 10. STATIC-ONLY enforcement  --  no subprocess, no external CLI execution
#     (This is the N+6.37A hardening that unblocks the Codex N+6.37B gate.)
# ---------------------------------------------------------------------------

# Needles assembled from fragments so the contiguous literal never appears in
# THIS test file either  --  the scan inspects the wrapper, not us, but we keep it
# clean for symmetry.
_EXEC_NEEDLES = [
    "subprocess" + ".run",
    "subprocess" + ".Popen",
    "subprocess" + ".call",
    "subprocess" + ".check_output",
    "Popen" + "(",
    "os" + ".system",
    "os" + ".popen",
    "os" + ".execv",
    "os" + ".spawn",
    "pty" + ".spawn",
]
_IMPORT_NEEDLES = [
    "import " + "subprocess",
    "import " + "pty",
]


class TestStaticOnlyNoSubprocess(unittest.TestCase):
    def _wrapper_text(self) -> str:
        return (_WRAPPER_DIR / "ghoti_claude_swarm_dry_run.py").read_text(
            encoding="utf-8", errors="replace"
        )

    def _ps1_text(self) -> str:
        return (_WRAPPER_DIR / "check_claude_swarm_dry_run.ps1").read_text(
            encoding="utf-8", errors="replace"
        )

    def test_wrapper_source_has_no_subprocess_import(self):
        src = inspect.getsource(_wrapper)
        tree = ast.parse(src)
        for node in ast.walk(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                mod = getattr(node, "module", None) or ""
                for alias in getattr(node, "names", []):
                    name = alias.name or ""
                    self.assertNotEqual(name, "subprocess",
                                        "wrapper imports subprocess")
                    self.assertNotEqual(name, "pty", "wrapper imports pty")
                self.assertNotEqual(mod, "subprocess",
                                    "wrapper imports from subprocess")

    def test_wrapper_source_has_no_exec_primitives(self):
        text = self._wrapper_text()
        for needle in _EXEC_NEEDLES + _IMPORT_NEEDLES:
            self.assertNotIn(
                needle, text,
                f"execution primitive {needle!r} present in wrapper",
            )

    def test_powershell_checker_no_invoke_expression(self):
        text = self._ps1_text()
        for needle in ["Invoke" + "-Expression", "Start" + "-Process"]:
            self.assertNotIn(needle, text,
                             f"{needle!r} present in PowerShell checker")
        # The checker must not invoke the external claude-swarm CLI directly.
        self.assertNotIn("& claude-swarm", text)
        self.assertNotIn("&claude-swarm", text)

    def test_check_source_scan_clean(self):
        result = _wrapper._run_check()
        self.assertIn("source_scan", result)
        self.assertTrue(result["source_scan_clean"],
                        f"source scan not clean: {result['source_scan']}")
        self.assertEqual(result["source_scan"]["wrapper"], [])
        self.assertEqual(result["source_scan"]["ps1"], [])

    def test_check_does_not_execute_external_cli(self):
        result = _wrapper._run_check()
        self.assertFalse(result["external_cli_executed"])
        self.assertFalse(result["subprocess_used"])
        self.assertFalse(result["provider_called"])
        self.assertFalse(result["agents_launched"])

    def test_probe_does_not_execute_external_cli(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _wrapper._run_probe()
        self.assertFalse(result["external_cli_executed"])
        self.assertFalse(result["subprocess_used"])
        self.assertFalse(result["provider_called"])
        self.assertFalse(result["agents_launched"])
        self.assertIsNone(result.get("probe_result"))

    def test_demo_does_not_execute_external_cli(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _wrapper._run_demo_mode()
        self.assertFalse(result["external_cli_executed"])
        self.assertFalse(result["subprocess_used"])
        self.assertFalse(result["provider_called"])
        self.assertFalse(result["agents_launched"])

    def test_all_modes_have_static_only_fields(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        for result in (_wrapper._run_check(), _wrapper._run_probe(),
                       _wrapper._run_demo_mode()):
            for field in ("external_cli_executed", "subprocess_used",
                          "provider_called", "api_key_used",
                          "agents_launched", "live_execution"):
                self.assertIn(field, result, f"{field} missing in {result['mode']}")
                self.assertFalse(result[field],
                                 f"{field} should be False in {result['mode']}")
            self.assertTrue(result["simulation"])

    def test_safety_block_has_static_only_flags(self):
        sb = _wrapper._SAFETY_BLOCK
        self.assertFalse(sb["external_cli_executed"])
        self.assertFalse(sb["subprocess_used"])
        self.assertFalse(sb["provider_called"])
        self.assertFalse(sb["agents_launched"])
        self.assertFalse(sb["third_party_code_executed"])

    def test_no_third_party_code_executed_in_demo(self):
        for k in _wrapper._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _wrapper._run_demo_mode()
        self.assertFalse(result["safety_block"]["third_party_code_executed"])


# ---------------------------------------------------------------------------
# 11. ASCII-safe regression -- PowerShell and Python files must be ASCII-only
#     (N+6.37A PS1 parse fix: em-dash / en-dash caused Windows PS parse error)
# ---------------------------------------------------------------------------

_N6_37A_FILES = [
    _WRAPPER_DIR / "check_claude_swarm_dry_run.ps1",
    _WRAPPER_DIR / "ghoti_claude_swarm_dry_run.py",
    _WRAPPER_DIR.parent.parent
        / "01_projects" / "runtime_mvp" / "tests"
        / "test_n6_37a_claude_swarm_isolated_dry_run.py",
]


class TestAsciiSafe(unittest.TestCase):
    def _check_ascii(self, path: Path) -> None:
        raw = path.read_bytes()
        bad = [(i, raw[i]) for i in range(len(raw)) if raw[i] > 127]
        if bad:
            newline = b"\n"
            samples = ", ".join(
                "pos {} 0x{:02x} line {}".format(i, b, raw[:i].count(newline) + 1)
                for i, b in bad[:5]
            )
            self.fail(
                "{} contains {} non-ASCII byte(s): {}".format(
                    path.name, len(bad), samples
                )
            )

    def test_ps1_checker_is_ascii_only(self):
        self._check_ascii(_WRAPPER_DIR / "check_claude_swarm_dry_run.ps1")

    def test_python_wrapper_is_ascii_only(self):
        self._check_ascii(_WRAPPER_DIR / "ghoti_claude_swarm_dry_run.py")

    def test_test_file_is_ascii_only(self):
        test_path = (
            Path(__file__).resolve().parent
            / "test_n6_37a_claude_swarm_isolated_dry_run.py"
        )
        self._check_ascii(test_path)


if __name__ == "__main__":
    unittest.main()
