"""
test_n6_38a_claude_swarm_fixture_replay.py  --  N+6.38A test suite.

Tests:
- no external CLI execution
- no provider/API key use
- fixture loads
- schema validates
- overlap detection works
- live launch blocks
- non-fixture path blocks
- Agent Arena output has simulation=true, live_execution=false
- no third-party code committed
- no secrets
- no AI attribution
- no real local paths in output
- parallel group ordering
- dependency validation
"""
from __future__ import annotations

import ast
import inspect
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

_WRAPPER_DIR = (
    Path(__file__).resolve().parent.parent.parent.parent
    / "03_scripts"
    / "claude_swarm_fixture"
)
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent

if str(_WRAPPER_DIR) not in sys.path:
    sys.path.insert(0, str(_WRAPPER_DIR))

import ghoti_claude_swarm_fixture_replay as _replay


def _repo_root() -> Path:
    return _REPO_ROOT


def _default_fixture() -> Path:
    return _repo_root() / "14_context" / "claude_swarm_fixture" / "sample_claude_swarm_plan.json"


def _load_fixture() -> dict:
    return json.loads(_default_fixture().read_text())


def _make_fixture(**overrides) -> dict:
    base = _load_fixture()
    base.update(overrides)
    return base


# ---------------------------------------------------------------------------
# 1. Source safety
# ---------------------------------------------------------------------------

class TestSourceSafety(unittest.TestCase):
    def test_no_ai_attribution(self):
        path = _WRAPPER_DIR / "ghoti_claude_swarm_fixture_replay.py"
        text = path.read_text().lower()
        for phrase in ["co-authored-by claude", "generated with claude",
                       "generated by claude", "written by claude"]:
            self.assertNotIn(phrase, text, f"AI attribution: {phrase!r}")

    def test_no_api_key_hardcoded(self):
        path = _WRAPPER_DIR / "ghoti_claude_swarm_fixture_replay.py"
        text = path.read_text()
        self.assertNotIn("sk-ant-", text)

    def test_wrapper_does_not_import_claude_swarm(self):
        src = inspect.getsource(_replay)
        tree = ast.parse(src)
        for node in ast.walk(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                for alias in getattr(node, "names", []):
                    self.assertNotIn("claude_swarm", alias.name or "")

    def test_no_subprocess_launch(self):
        src = inspect.getsource(_replay)
        tree = ast.parse(src)
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = node.func
                if isinstance(func, ast.Attribute) and func.attr in ("run", "call", "Popen"):
                    if isinstance(func.value, ast.Name) and func.value.id == "subprocess":
                        self.fail("Wrapper uses subprocess to launch processes")

    def test_no_third_party_code_committed(self):
        result = subprocess.run(
            ["git", "-C", str(_repo_root()), "ls-files",
             "21_repos/third_party_runtime_sandbox/claude_swarm"],
            capture_output=True, text=True,
        )
        self.assertEqual(result.stdout.strip(), "")


# ---------------------------------------------------------------------------
# 2. Fixture loading and schema validation
# ---------------------------------------------------------------------------

class TestFixtureLoading(unittest.TestCase):
    def test_default_fixture_exists(self):
        self.assertTrue(_default_fixture().exists())

    def test_fixture_loads_as_json(self):
        data = _load_fixture()
        self.assertIsInstance(data, dict)

    def test_fixture_has_required_fields(self):
        data = _load_fixture()
        for field in ("fixture_id", "source", "swarm", "tasks", "safety"):
            self.assertIn(field, data)

    def test_fixture_source_is_static(self):
        data = _load_fixture()
        self.assertEqual(data["source"], "static_fixture")

    def test_fixture_simulation_true(self):
        data = _load_fixture()
        self.assertTrue(data["swarm"]["simulation"])
        self.assertTrue(data["safety"]["simulation"])

    def test_fixture_live_execution_false(self):
        data = _load_fixture()
        self.assertFalse(data["swarm"]["live_execution"])
        self.assertFalse(data["safety"]["live_execution"])

    def test_fixture_dry_run_true(self):
        data = _load_fixture()
        self.assertTrue(data["swarm"]["dry_run"])

    def test_fixture_has_tasks(self):
        data = _load_fixture()
        self.assertGreater(len(data["tasks"]), 0)

    def test_schema_validates_clean_fixture(self):
        data = _load_fixture()
        errors = _replay._validate_fixture_schema(data)
        self.assertEqual(errors, [], f"Schema errors: {errors}")


# ---------------------------------------------------------------------------
# 3. Schema validation catches bad fixtures
# ---------------------------------------------------------------------------

class TestSchemaValidation(unittest.TestCase):
    def _bad_fixture(self, **overrides) -> dict:
        f = _load_fixture()
        def deep_set(d, keys, value):
            for k in keys[:-1]:
                d = d[k]
            d[keys[-1]] = value
        for key, value in overrides.items():
            if "." in key:
                parts = key.split(".")
                deep_set(f, parts, value)
            else:
                f[key] = value
        return f

    def test_wrong_source_rejected(self):
        data = self._bad_fixture(source="live_run")
        errors = _replay._validate_fixture_schema(data)
        self.assertTrue(any("source" in e for e in errors))

    def test_live_execution_true_rejected(self):
        f = _load_fixture()
        f["swarm"]["live_execution"] = True
        errors = _replay._validate_fixture_schema(f)
        self.assertTrue(any("live_execution" in e for e in errors))

    def test_simulation_false_rejected(self):
        f = _load_fixture()
        f["swarm"]["simulation"] = False
        errors = _replay._validate_fixture_schema(f)
        self.assertTrue(any("simulation" in e for e in errors))

    def test_safety_live_agent_launch_true_rejected(self):
        f = _load_fixture()
        f["safety"]["live_agent_launch"] = True
        errors = _replay._validate_fixture_schema(f)
        self.assertTrue(any("live_agent_launch" in e for e in errors))

    def test_duplicate_task_id_rejected(self):
        f = _load_fixture()
        f["tasks"].append({**f["tasks"][0]})
        errors = _replay._validate_fixture_schema(f)
        self.assertTrue(any("duplicate" in e for e in errors))


# ---------------------------------------------------------------------------
# 4. Overlap detection
# ---------------------------------------------------------------------------

class TestOverlapDetection(unittest.TestCase):
    def test_no_overlaps_in_clean_fixture(self):
        data = _load_fixture()
        overlaps = _replay._detect_file_overlaps(data["tasks"])
        self.assertEqual(overlaps, [])

    def test_overlaps_detected(self):
        tasks = [
            {"id": "t1", "files_to_modify": ["src/auth.ts"], "dependencies": []},
            {"id": "t2", "files_to_modify": ["src/auth.ts"], "dependencies": []},
        ]
        overlaps = _replay._detect_file_overlaps(tasks)
        self.assertEqual(len(overlaps), 1)
        self.assertEqual(overlaps[0]["file"], "src/auth.ts")
        self.assertIn("t1", overlaps[0]["claimed_by"])
        self.assertIn("t2", overlaps[0]["claimed_by"])

    def test_no_overlap_different_files(self):
        tasks = [
            {"id": "t1", "files_to_modify": ["a.ts"], "dependencies": []},
            {"id": "t2", "files_to_modify": ["b.ts"], "dependencies": []},
        ]
        self.assertEqual(_replay._detect_file_overlaps(tasks), [])


# ---------------------------------------------------------------------------
# 5. Parallel group ordering
# ---------------------------------------------------------------------------

class TestParallelGroups(unittest.TestCase):
    def test_independent_tasks_in_first_group(self):
        data = _load_fixture()
        groups = _replay._build_parallel_groups(data["tasks"])
        self.assertGreater(len(groups), 0)
        # task-1 and task-2 have no dependencies  --  should be in first group
        first = groups[0]
        self.assertIn("task-1", first)
        self.assertIn("task-2", first)

    def test_dependent_tasks_in_later_group(self):
        data = _load_fixture()
        groups = _replay._build_parallel_groups(data["tasks"])
        flat = [tid for g in groups for tid in g]
        # task-5 depends on task-1, task-2, task-3  --  must come after all three
        if "task-5" in flat and "task-1" in flat:
            self.assertGreater(flat.index("task-5"), flat.index("task-1"))

    def test_all_tasks_covered(self):
        data = _load_fixture()
        groups = _replay._build_parallel_groups(data["tasks"])
        flat = {tid for g in groups for tid in g}
        all_ids = {t["id"] for t in data["tasks"]}
        self.assertEqual(flat, all_ids)


# ---------------------------------------------------------------------------
# 6. Blocked paths
# ---------------------------------------------------------------------------

class TestBlockedPaths(unittest.TestCase):
    def test_non_json_path_blocked(self):
        errors = _replay._validate_fixture_path(Path("/tmp/plan.yaml"))
        self.assertTrue(any("json" in e for e in errors))

    def test_etc_path_blocked(self):
        errors = _replay._validate_fixture_path(Path("/etc/passwd.json"))
        self.assertTrue(any("blocked_path_pattern" in e for e in errors))

    def test_env_path_blocked(self):
        errors = _replay._validate_fixture_path(Path("/home/user/.env.json"))
        self.assertTrue(any("blocked_path_pattern" in e for e in errors))

    def test_valid_json_path_allowed(self):
        with tempfile.TemporaryDirectory() as tmp:
            p = Path(tmp) / "fixture.json"
            errors = _replay._validate_fixture_path(p)
            self.assertEqual(errors, [])


# ---------------------------------------------------------------------------
# 7. API key refusal
# ---------------------------------------------------------------------------

class TestApiKeyRefusal(unittest.TestCase):
    def test_replay_blocked_when_api_key_set(self):
        os.environ["ANTHROPIC_API_KEY"] = "fake-key"
        try:
            result = _replay._run_replay()
            self.assertFalse(result["ok"])
            self.assertEqual(result["error"], "api_keys_present")
        finally:
            del os.environ["ANTHROPIC_API_KEY"]

    def test_replay_ok_without_api_key(self):
        for k in _replay._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _replay._run_replay()
        self.assertTrue(result["ok"], f"Expected ok=True, got: {result}")


# ---------------------------------------------------------------------------
# 8. Agent Arena status shape
# ---------------------------------------------------------------------------

class TestArenaStatus(unittest.TestCase):
    def test_safety_block_simulation_true(self):
        self.assertTrue(_replay._SAFETY_BLOCK["simulation"])

    def test_safety_block_live_execution_false(self):
        self.assertFalse(_replay._SAFETY_BLOCK["live_execution"])

    def test_safety_block_external_cli_false(self):
        self.assertFalse(_replay._SAFETY_BLOCK["external_cli_executed"])

    def test_safety_block_provider_called_false(self):
        self.assertFalse(_replay._SAFETY_BLOCK["provider_called"])

    def test_replay_result_simulation_true(self):
        for k in _replay._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _replay._run_replay()
        self.assertTrue(result.get("simulation"))
        self.assertFalse(result.get("live_execution"))

    def test_replay_external_cli_not_executed(self):
        for k in _replay._API_KEY_ENV_VARS:
            os.environ.pop(k, None)
        result = _replay._run_replay()
        self.assertFalse(result.get("external_cli_executed"))
        self.assertFalse(result.get("agents_launched"))
        self.assertFalse(result.get("provider_called"))


# ---------------------------------------------------------------------------
# 9. Check mode
# ---------------------------------------------------------------------------

class TestCheckMode(unittest.TestCase):
    def test_check_ok(self):
        result = _replay._run_check()
        self.assertTrue(result["ok"])

    def test_check_milestone(self):
        result = _replay._run_check()
        self.assertEqual(result["milestone"], "N+6.38A")

    def test_check_external_cli_blocked(self):
        result = _replay._run_check()
        self.assertIn("BLOCKED", result.get("external_cli_execution", ""))

    def test_check_has_safety_block(self):
        result = _replay._run_check()
        sb = result["safety_block"]
        self.assertTrue(sb["simulation"])
        self.assertFalse(sb["live_execution"])

    def test_check_start_conditions_documented(self):
        result = _replay._run_check()
        sc = result["start_conditions"]
        self.assertIn("n6_35b_on_main", sc)
        self.assertIn("n6_36b_on_main", sc)
        self.assertIn("n6_37b_on_main", sc)


# ---------------------------------------------------------------------------
# 10. Full replay
# ---------------------------------------------------------------------------

class TestFullReplay(unittest.TestCase):
    def setUp(self):
        for k in _replay._API_KEY_ENV_VARS:
            os.environ.pop(k, None)

    def test_replay_accepted(self):
        result = _replay._run_replay()
        self.assertTrue(result.get("accepted"))

    def test_replay_has_plan_summary(self):
        result = _replay._run_replay()
        self.assertIn("plan_summary", result)

    def test_replay_task_count_correct(self):
        result = _replay._run_replay()
        fixture = _load_fixture()
        self.assertEqual(result["plan_summary"]["task_count"], len(fixture["tasks"]))

    def test_replay_no_real_paths_in_output(self):
        result = _replay._run_replay()
        output_str = json.dumps(result)
        for path in ["/home/user/", "C:\\Users\\", "/root/"]:
            # fixture_path itself may contain the repo path  --  check plan content only
            plan_str = json.dumps(result.get("plan_summary", {}))
            self.assertNotIn(path, plan_str, f"Machine path in plan_summary: {path}")

    def test_replay_has_next_step(self):
        result = _replay._run_replay()
        self.assertIn("next_step", result)


class TestAsciiSafe(unittest.TestCase):
    """Regression tests: no non-ASCII bytes in committed N+6.38A files."""

    def _check_ascii(self, path: Path) -> None:
        raw = path.read_bytes()
        bad = [(i, raw[i]) for i in range(len(raw)) if raw[i] > 127]
        if bad:
            newline = b"\n"
            samples = ", ".join(
                "pos {} 0x{:02x} line {}".format(i, b, raw[:i].count(newline) + 1)
                for i, b in bad[:5]
            )
            self.fail(
                "{} contains {} non-ASCII byte(s): {}".format(
                    path.name, len(bad), samples
                )
            )

    def test_ps1_checker_is_ascii_only(self):
        self._check_ascii(_WRAPPER_DIR / "check_claude_swarm_fixture_replay.ps1")

    def test_python_wrapper_is_ascii_only(self):
        self._check_ascii(_WRAPPER_DIR / "ghoti_claude_swarm_fixture_replay.py")

    def test_test_file_is_ascii_only(self):
        self._check_ascii(Path(__file__).resolve())


if __name__ == "__main__":
    unittest.main()
